on:
  workflow_dispatch:
    inputs:
      tag:
        description: Tag name starting with v, e.g. v2.0.3
        type: string
        required: true
        
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - run: |
          hub release create \
          --draft \
          ${{ inputs.tag }}

