on:
  workflow_dispatch:
    inputs:
      tag:
        description: Tag name starting with v, e.g. v2.0.3
        type: string
        required: true
        
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          sparse-checkout: |
            Operations/*
            Subseasonal/pycpt-s2s.ipynb
          sparse-checkout-cone-mode: false
      - run: |
          gh release create \
          --draft \
          "${{ inputs.tag }}" \
          Operations/pycpt-operational.ipynb \
          Operations/pycpt-operational.py \
          Subseasonal/pycpt-s2s.ipynb \
          Operations/conda-win-64.lock \
          Operations/conda-osx-64.lock \
          Operations/conda-linux-64.lock
        env:
          GITHUB_TOKEN: "${{ github.token }}"

