on:
  workflow_dispatch:
    inputs:
      tag:
        description: Tag name starting with v, e.g. v2.0.3
        type: string
        required: true
        
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          sparse-checkout: |
            Operations/pycpt-operational.ipynb
            Operations/conda-*.lock
          sparse-checkout-cone-mode: false
      - run: |
          hub release create \
          --draft \
          --attach Operations/pycpt-operational.ipynb \
          --attach Operations/conda-win-64.lock \
          --attach Operations/conda-osx-64.lock \
          --attach Operations/conda-linux-64.lock \
          --message "${{ inputs.tag }}" \
          "${{ inputs.tag }}"
        env:
          GITHUB_TOKEN: "${{ github.token }}"

