on:
  workflow_dispatch:
    inputs:
      tag:
        description: Tag name starting with v, e.g. v2.0.3
        type: string
        required: true
        
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          hub release create \
          --draft \
          --attach Operations/* \
          --message "${{ inputs.tag }}" \
          "${{ inputs.tag }}"
        env:
          GITHUB_TOKEN: "${{ github.token }}"

